version: '3.8'

services:
  api:
    build:
      context: ./API
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app
    env_file:
      - ./API/.env
    # No necesitas `depends_on` para `db` ya que SQLite es un archivo local

  frontend:
    build:
      context: ./Frontend
    container_name: streamlit_service
    ports:
      - "8501:8501"
    volumes:
      - ./Frontend:/app
    depends_on:
      - api
  
  # El servicio `db` ha sido eliminado ya que SQLite no necesita un contenedor separado
